### ISSUE TITLE
몇가지 Issue 정리.

### ISSUE THREAD

**Issue by mgwoo** [dhguswns23/hexa_bus#1]
React를 설정 하는 방법을 모르겠어서(..), 

그냥 /test/index.html에서 js와 css의 location을 
상대좌표로 dist안에것을 참조하도록 manual 하게 수정하니 돌아가는것을 확인. 
이것을 기준으로 이슈를 작성함. 

1. Swipe 메뉴 적용부탁...
2. 깨져나오는 한글 확인 부탁.. (카톡으로 전달 완료)
3. 카카오톡도 연동되게 확인 부탁!
4. Notice에서 \n을 <br />태그에 매핑하는것 확인 부탁.. (\<s>, \<b>tag도 예외처리 해주면 ㄳ요..)
5. 맨 밑에 You can check detail code on here. footer 제거 부탁.
6. Notice 아까 이야기했듯이 이미지로 예쁘게 포장하는 느낌나게 하는게 PR면에서 괜찮을듯!
(나 이런거 만들었어요~)
7. 창 크기를 조절 할 때에 2열일 때에 (중간 폭으로 브라우저 크기 변경) 위에 Title이랑 밑에 박스가 안맞는게 조금 거슬린다고 하네.. 고칠수 있으면 고쳐주시면 Vㅔ리 감사.
개발자 도구로 확인하니 section class="content" 내부에  div class="each"가 margin을 1%씩 먹네.. 이거 없애고 width를 조금 늘리는게 더 보기 나아보일듯
8. (22 정거장 전) -> (22 전) 으로 수정하면 2줄로 안나오게 깔끔하게 잘릴듯. 
만약 그게 힘들면 
<b>삼호주공아파트앞</b>
(17 정거장 전)
이렇게 두개 잘리도록 div나 span설정하는 것도 나을듯.
9. 창의 폭이 매우 좁은경우(1열인 경우), UNIST 입구 같은 경우 
UNIST입
구
와 같이 나오는 현상이 발견됨.
개발자 도구로 확인하니 
div class=inner-wrapper 안에 div class=name의 width 가 35%던데.. 
이거 60~70%로 올려도 문제 없어보임.
10. JSON으로 뿌려주는 Subtitle에도 \n있는데
KTX울산역, 언양정류장 방향\n(J:작천정, D:대곡) 일텐데..
\n의 escape를 풀어주세요오오오... (\<br />으로 replace도 굿..)
11. 그거 로딩중일때 다른거 누르면 로딩중입니다. 하고 다른거 실행 안되는거.. 해제 하는게 좋아보임. 
만약에 서비스가 작동안할때 무한 작동 안됨현상이 일어날 수 있을것 같아서 우려..

**Comment by dhguswns23** [comment]
확인완료!

**Comment by dhguswns23** [comment]
3, 6번 외 해결 완료!
