### ISSUE TITLE
Swipe region 조절

### ISSUE THREAD

**Issue by mgwoo** [dhguswns23/hexa_bus#10]
https://www.facebook.com/UnistDaejeon/posts/1838884799735420
유대전에서 제보가 들어옴.

현재 모바일에서 확인된 바로는-
swipe가 되긴 되는데 왼끝에서 진짜 겨우 끌어다 당겨야 열리는 수준..
확인해서 region을 조금 더 키우는 방향으로 하는것이 어떨지..

**Comment by dhguswns23** [comment]
터치 범위 2배로 늘려서 해결완료!
