### ISSUE TITLE
하드코딩된 Menu들을 json으로 연동

### ISSUE THREAD

**Issue by mgwoo** [dhguswns23/hexa_bus#6]
현재 자체가 하드코딩되어있어 back 단에서 수정하기 쉽게 하기 위해
기존 메뉴를 http://bus.hexa.pro/bus/get_menu_info.php?debug=1에서 받아와주십사 합니다.
(추후 수정할 일 있으면 그냥 쉽게 저것만 고쳐버리게)

**Comment by dhguswns23** [comment]
수정 완료!
