### ISSUE TITLE
Hexa.Bus 글자 효과 및 잔여 버스 정류장 정보 관련..

### ISSUE THREAD

**Issue by mgwoo** [dhguswns23/hexa_bus#7]
처음에 있던 Hexa.Bus 간결한 글자체로 되어있던거 그대로 해주세요...
로딩될때마다 외곽선 반짝거리는거 너무 이상함..

그리고 
<b>마산입구</b>
(1 전)
이렇게 두줄로 나와있는거 생각보다 안예쁜데 그냥 \<br /> 없애고 한줄에 달리게 하고
글씨크기 조금 키우는게 보기 더 예쁠듯... 2줄 ㅈㅈ요..

**Comment by dhguswns23** [comment]
음... 정류장 이름이 길어지면 두줄로 되더라구요 ㅠㅠ 그래도 한줄로 일단 바꿀까요?

**Comment by dhguswns23** [comment]
수정완료!
