### ISSUE TITLE
uglifyjs를 이용한 js/css 용량 압축

### ISSUE THREAD

**Issue by mgwoo** [dhguswns23/hexa_bus#8]
(추석 끝나고 해도 늦지않는 이슈.. ㅎㅎ 메리추석마스)
기존 js 용량이 1.2MB인데
ugliftyjs를 이용하여 minimize하니 700kb 까지 감소되어
초반 접속일때 데이터 부담을 줄여줌.. 
(현재 bus.hexa.pro에서는 수작업으로 만들어 적용이 완료된 상태)

컴파일하면 자동으로 변환되는 방법 찾아주길 부탁드림..

**Comment by dhguswns23** [comment]
해결 완료!
