### ISSUE TITLE
Refresh 아이콘 추가

### ISSUE THREAD

**Issue by mgwoo** [dhguswns23/hexa_bus#9]
기존 디자인에서도 존재하던

오른쪽 위 Refresh형태의 새로고침 형태의 버튼을 넣어주었으면 매우 편하게 쓸듯..

**Comment by mgwoo** [comment]
https://www.facebook.com/UnistDaejeon/posts/1838884799735420 에서 제보 들어옴.
(내용은 같은내용)

**Comment by dhguswns23** [comment]
해결 완료!
